### ISSUE TITLE
Module hotel - AttributeError: 'list' object has no attribute '_onchange'

### ISSUE THREAD

**Issue by Vassy** [JayVora-SerpentCS/SerpentCS_Contributions-v8#11]
When install module hotel give these error:
2015-07-06 07:01:04,545 18067 ERROR bgacc openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo8/odoo/openerp/http.py", line 526, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo8/odoo/openerp/http.py", line 563, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo8/odoo/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo8/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo8/odoo/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo8/odoo/openerp/http.py", line 792, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo8/odoo/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo8/odoo/addons/web/controllers/main.py", line 953, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo8/odoo/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo8/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo8/odoo/openerp/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/opt/odoo8/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo8/odoo/openerp/addons/base/module/module.py", line 498, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/odoo8/odoo/openerp/modules/registry.py", line 366, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo8/odoo/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo8/odoo/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo8/odoo/openerp/modules/loading.py", line 156, in load_module_graph
    registry.setup_models(cr, partial=True)
  File "/opt/odoo8/odoo/openerp/modules/registry.py", line 194, in setup_models
    model._setup_complete(cr, SUPERUSER_ID)
  File "/opt/odoo8/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo8/odoo/openerp/api.py", line 336, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo8/odoo/openerp/models.py", line 3012, in _setup_complete
    _logger.warning("@onchange%r parameters must be field names", func._onchange)
AttributeError: 'list' object has no attribute '_onchange'

**Comment by JayVora-SerpentCS** [comment]
Please report to https://github.com/JayVora-SerpentCS/hotelmgmt_v8/issues! It has been fixed in https://github.com/JayVora-SerpentCS/hotelmgmt_v8/pull/11
