### ISSUE TITLE
[V11] Web digital sign - error occurred

### ISSUE THREAD

**Issue by simoneversienti** [JayVora-SerpentCS/SerpentCS_Contributions-v8#158]
Hi, i've installed your module web_digital_sign on Odoo 11 but when in the users' tab i obtain this error.
`Errore:
Uncaught TypeError: Cannot read property 'string' of undefined

http://0.0.0.0:8069/web/content/252-0e9eff1/web.assets_backend.js:1358
Traceback:
TypeError: Cannot read property 'string' of undefined
    at Class._renderTagLabel (http://0.0.0.0:8069/web/content/252-0e9eff1/web.assets_backend.js:1358:776)
    at Class._renderInnerGroupLabel (http://0.0.0.0:8069/web/content/252-0e9eff1/web.assets_backend.js:1349:105)
    at http://0.0.0.0:8069/web/content/252-0e9eff1/web.assets_backend.js:1346:114
    at Function._.each._.forEach (http://0.0.0.0:8069/web/content/241-50b2dc8/web.assets_common.js:12:558)
    at Class._renderInnerGroup (http://0.0.0.0:8069/web/content/252-0e9eff1/web.assets_backend.js:1343:63)
    at Class._renderTagGroup (http://0.0.0.0:8069/web/content/252-0e9eff1/web.assets_backend.js:1356:242)
    at Class._renderNode (http://0.0.0.0:8069/web/content/252-0e9eff1/web.assets_backend.js:1349:246)
    at Function._.map._.collect (http://0.0.0.0:8069/web/content/241-50b2dc8/web.assets_common.js:13:270)
    at Class._renderTagForm (http://0.0.0.0:8069/web/content/252-0e9eff1/web.assets_backend.js:1356:18)
    at Class._renderNode (http://0.0.0.0:8069/web/content/252-0e9eff1/web.assets_backend.js:1349:246)`

**Comment by JayVora-SerpentCS** [comment]
We have yet to migrate the module.

**Comment by JayVora-SerpentCS** [comment]
Migrated the module and fixed it.
