### ISSUE TITLE
Sync Error with  moduel sync Muilt daabase in Odoo9

### ISSUE THREAD

**Issue by ibrahimtoma** [JayVora-SerpentCS/SerpentCS_Contributions-v8#159]
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo/openerp/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/openerp/http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/openerp/http.py", line 323, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/http.py", line 316, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/openerp/http.py", line 966, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/openerp/http.py", line 516, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 899, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 887, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 381, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo/addons/base_synchro/wizard/base_synchro.py", line 280, in upload_download_multi_thread
    threading.Thread(target=self.upload_download())
  File "/opt/odoo/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/addons/base_synchro/wizard/base_synchro.py", line 245, in upload_download
    self.synchronize(server, obj_rec)
  File "/opt/odoo/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/addons/base_synchro/wizard/base_synchro.py", line 76, in synchronize
    {'action': 'd'})
  File "/opt/odoo/odoo/addons/base_synchro/wizard/base_synchro.py", line 34, in <lambda>
    self.ressource, name, *args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1316, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1493, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 800, in close
    raise Fault(**self._stack[0])
Fault: <Fault operator does not exist: integer = boolean
LINE 1: ...T password, password_crypt FROM res_users WHERE id=false AND...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
: 'Traceback (most recent call last):\n  File "/opt/odoo/odoo/openerp/service/wsgi_server.py", line 56, in xmlrpc_return\n    result = openerp.http.dispatch_rpc(service, method, params)\n  File "/opt/odoo/odoo/openerp/http.py", line 115, in dispatch_rpc\n    result = dispatch(method, params)\n  File "/opt/odoo/odoo/openerp/service/model.py", line 34, in dispatch\n    security.check(db,uid,passwd)\n  File "/opt/odoo/odoo/openerp/service/security.py", line 13, in check\n    return res_users.check(db, uid, passwd)\n  File "/opt/odoo/odoo/addons/base/res/res_users.py", line 509, in check\n    self.check_credentials(cr, uid, passwd)\n  File "/opt/odoo/odoo/openerp/api.py", line 250, in wrapper\n    return old_api(self, *args, **kwargs)\n  File "/opt/odoo/odoo/addons/auth_crypt/auth_crypt.py", line 51, in check_credentials\n    cr.execute(\'SELECT password, password_crypt FROM res_users WHERE id=%s AND active\', (uid,))\n  File "/opt/odoo/odoo/openerp/sql_db.py", line 141, in wrapper\n    return f(self, *args, **kwargs)\n  File "/opt/odoo/odoo/openerp/sql_db.py", line 220, in execute\n    res = self._obj.execute(query, params)\nProgrammingError: operator does not exist: integer = boolean\nLINE 1: ...T password, password_crypt FROM res_users WHERE id=false AND...\n                                                             ^\nHINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.\n\n'>

**Comment by ibrahimtoma** [comment]
i searched for solution but don`t reach to any solution... i see merge pull request #103 from chandresh ...
can i test his solution in Odoo9 !!! If No.
Can U help Me ?

**Comment by JayVora-SerpentCS** [comment]
You may test
