### ISSUE TITLE
Base_synchro Module error while synching with other database

### ISSUE THREAD

**Issue by atuljain** [JayVora-SerpentCS/SerpentCS_Contributions-v8#17]
I watched video on youtube and according to that i configure my database but still i am getting error can someone check it 
Traceback (most recent call last):
  File "/mongodata/odoo/openerp/http.py", line 524, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/mongodata/odoo/openerp/http.py", line 545, in dispatch
    result = self._call_function(**self.params)
  File "/mongodata/odoo/openerp/http.py", line 301, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/mongodata/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/mongodata/odoo/openerp/http.py", line 298, in checked_call
    return self.endpoint(*a, **kw)
  File "/mongodata/odoo/openerp/http.py", line 761, in __call__
    return self.method(*args, **kw)
  File "/mongodata/odoo/openerp/http.py", line 394, in response_wrap
    response = f(*args, **kw)
  File "/mongodata/odoo/addons/web/controllers/main.py", line 953, in call_button
    action = self._call_kw(model, method, args, {})
  File "/mongodata/odoo/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/mongodata/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/mongodata/odoo/addons/base_synchro/wizard/base_synchro.py", line 277, in upload_download_multi_thread
    threaded_synchronization.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/mongodata/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/mongodata/odoo/addons/base_synchro/wizard/base_synchro.py", line 244, in upload_download
    self.synchronize(cr, uid, server, object, context=context)
  File "/mongodata/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/mongodata/odoo/addons/base_synchro/wizard/base_synchro.py", line 125, in synchronize
    value = self.data_transform(cr, uid, pool_src, pool_dest, object.model_id.model, value, action, context=context)
  File "/mongodata/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/mongodata/odoo/addons/base_synchro/wizard/base_synchro.py", line 220, in data_transform
    df = self.relation_transform(cr, uid, pool_src, pool_dest, fields[f]['relation'], fdata, action, context=context)
  File "/mongodata/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/mongodata/odoo/addons/base_synchro/wizard/base_synchro.py", line 188, in relation_transform
    res = pool_dest.get(object).name_search(cr, uid, names, [], 'like')
AttributeError: 'NoneType' object has no attribute 'name_search'

**Comment by JayVora-SerpentCS** [comment]
@atuljain , master of v8 ?

**Comment by atuljain** [comment]
v-8

**Comment by JayVora-SerpentCS** [comment]
@atuljain , master of v8 ?
