### ISSUE TITLE
Mass Label Reporting (odoo11)

### ISSUE THREAD

**Issue by DukeII** [JayVora-SerpentCS/SerpentCS_Contributions-v8#175]
Hi
config
odoo11-community-winows-local

installed this module but error

best regards , any idea what causes this error ?

odoo.log
2018-02-07 07:47:14,881 336 INFO odoo11 werkzeug: 127.0.0.1 - - [07/Feb/2018 07:47:14] "POST /longpolling/poll HTTP/1.1" 200 -
2018-02-07 07:47:19,920 336 INFO odoo11 werkzeug: 127.0.0.1 - - [07/Feb/2018 07:47:19] "POST /web/dataset/call_button HTTP/1.1" 200 -
2018-02-07 07:47:19,951 336 INFO ? werkzeug: 127.0.0.1 - - [07/Feb/2018 07:47:19] "GET /web/static/src/img/spin.png HTTP/1.1" 200 -
2018-02-07 07:47:20,076 336 INFO odoo11 werkzeug: 127.0.0.1 - - [07/Feb/2018 07:47:20] "POST /report/download HTTP/1.1" 200 -

Error:
Odoo Server Error

Traceback (most recent call last):
  File "D:\odoo11\Odoo 11.0\server\odoo\addons\base\ir\ir_qweb\qweb.py", line 341, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_925_70
  File "<template>", line 2, in body_call_content_69
  File "<template>", line 3, in body_call_content_68
  File "D:\odoo11\addons\label\report\dynamic_label.py", line 87, in get_data
    for row in range(0, len(result) / (columns) + 1):
TypeError: 'float' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\odoo11\Odoo 11.0\server\odoo\addons\web\controllers\main.py", line 1667, in report_download
    response = self.report_routes(reportname, converter='pdf', **dict(data))
  File "D:\odoo11\Odoo 11.0\server\odoo\http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "D:\odoo11\Odoo 11.0\server\odoo\addons\web\controllers\main.py", line 1612, in report_routes
    pdf = report.with_context(context).render_qweb_pdf(docids, data=data)[0]
  File "D:\odoo11\Odoo 11.0\server\odoo\addons\base\ir\ir_actions_report.py", line 624, in render_qweb_pdf
    html = self.with_context(context).render_qweb_html(res_ids, data=data)[0]
  File "D:\odoo11\Odoo 11.0\server\odoo\addons\base\ir\ir_actions_report.py", line 662, in render_qweb_html
    return self.render_template(self.report_name, data), 'html'
  File "D:\odoo11\Odoo 11.0\server\odoo\addons\base\ir\ir_actions_report.py", line 470, in render_template
    return view_obj.render_template(template, values)
  File "D:\odoo11\Odoo 11.0\server\odoo\addons\base\ir\ir_ui_view.py", line 1158, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "D:\odoo11\Odoo 11.0\server\odoo\addons\web_editor\models\ir_ui_view.py", line 27, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "D:\odoo11\Odoo 11.0\server\odoo\addons\base\ir\ir_ui_view.py", line 1167, in render
    return self.env[engine].render(self.id, qcontext)
  File "D:\odoo11\Odoo 11.0\server\odoo\addons\base\ir\ir_qweb\ir_qweb.py", line 57, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "D:\odoo11\Odoo 11.0\server\odoo\addons\base\ir\ir_qweb\qweb.py", line 271, in render
    self.compile(template, options)(self, body.append, values or {})
  File "D:\odoo11\Odoo 11.0\server\odoo\addons\base\ir\ir_qweb\qweb.py", line 348, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.ir.ir_qweb.qweb.QWebException: 'float' object cannot be interpreted as an integer
Traceback (most recent call last):
  File "D:\odoo11\Odoo 11.0\server\odoo\addons\base\ir\ir_qweb\qweb.py", line 341, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_925_70
  File "<template>", line 2, in body_call_content_69
  File "<template>", line 3, in body_call_content_68
  File "D:\odoo11\addons\label\report\dynamic_label.py", line 87, in get_data
    for row in range(0, len(result) / (columns) + 1):
TypeError: 'float' object cannot be interpreted as an integer

Error to render compiling AST
TypeError: 'float' object cannot be interpreted as an integer
Template: 925
Path: /templates/t/t/t/div/div/table/t
Node: <t t-foreach="get_data(data['form'].get('rows'),data['form'].get('columns'),data['form'].get('ids'),data ['form'].get('model'),data['form'].get('number_of_copy'))" t-as="row">
                                <tr t-att-height="data['form']['height']">
                                    <t t-foreach="row" t-as="col">
                                        <td t-att-width="data['form']['width']" t-att-style="'padding-left:'+data['form']['left_margin']+';padding-right:'+data['form']['right_margin']+';padding-top:'+data['form']['top_margin']+';border:1px solid black;'">
                                            <t t-foreach="col" t-as="val">
                                                <t t-if="val['newline']">
                                                    <br data-oe-model="ir.ui.view" data-oe-id="925" data-oe-field="arch" data-oe-xpath="/t[1]/t[1]/t[1]/div[1]/div[1]/table[1]/t[1]/tr[1]/t[1]/td[1]/t[1]/t[1]/br[1]"/>
                                                </t>
                                                <span style="val['style']">
                                                    <t t-if="(val.get('type') == 'normal')">
                                                        <t t-esc="val['string']"/>
                                                        <t t-esc="val['value']"/>
                                                    </t>
                                                    <t t-if="(val.get('type') == 'image')">
                                                        <t t-esc="val.get('string')"/>
                                                        <img t-att-src="'data:image/png;base64,%s' % (val.get('value'))" t-att-style="'height:'+data['form']['image_height']+';width:'+data['form']['image_width']" data-oe-model="ir.ui.view" data-oe-id="925" data-oe-field="arch" data-oe-xpath="/t[1]/t[1]/t[1]/div[1]/div[1]/table[1]/t[1]/tr[1]/t[1]/td[1]/t[1]/span[1]/t[2]/img[1]"/>
                                                    </t>
                                                    <t t-if="(val.get('type') == 'barcode')">
                                                        <t t-esc="val.get('string')"/>
                                                        <img t-att-src="'/report/barcode/?type=%s&amp;value=%s&amp;width=%s&amp;height=%s' % ('Code128',val.get('value') , data['form']['barcode_width'], data['form']['barcode_height'])" data-oe-model="ir.ui.view" data-oe-id="925" data-oe-field="arch" data-oe-xpath="/t[1]/t[1]/t[1]/div[1]/div[1]/table[1]/t[1]/tr[1]/t[1]/td[1]/t[1]/span[1]/t[3]/img[1]"/>
                                                    </t>
                                                </span>
                                            </t>
                                        </td>
                                    </t>
                                </tr>
                            </t>

**Comment by JayVora-SerpentCS** [comment]
@shobhapadasalagi Do you receive this error ? Check the line of execution please.

**Comment by JayVora-SerpentCS** [comment]
#177
