### ISSUE TITLE
Base_Synchro error after delete record in destination database V10.

### ISSUE THREAD

**Issue by cor9003** [JayVora-SerpentCS/SerpentCS_Contributions-v8#184]
Hello,
If one object ( for example model res.partner)  in destination database has been deleted, if I modify the original record in the source database, the sync return an error because try to update the object in destination that not exist because was deleted manually.

The problem is once it happend it is not possible more syncs due to always is stopped for this error. 

Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 894, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/addons/web/controllers/main.py", line 882, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/custom/SerpentCS_Contributions/base_synchro/wizard/base_synchro.py", line 301, in upload_download_multi_thread
    threading.Thread(target=self.upload_download())
  File "/opt/odoo/custom/SerpentCS_Contributions/base_synchro/wizard/base_synchro.py", line 264, in upload_download
    self.synchronize(server, obj_rec)
  File "/opt/odoo/custom/SerpentCS_Contributions/base_synchro/wizard/base_synchro.py", line 139, in synchronize
    pool_dest.get(object.model_id.model).write([id2], value)
  File "/opt/odoo/custom/SerpentCS_Contributions/base_synchro/wizard/base_synchro.py", line 34, in <lambda>
    *args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1316, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1493, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 800, in close
    raise Fault(**self._stack[0])
Fault: <Fault warning -- MissingError

(u'Uno de los registros que est\xe1 intentando modificar ya ha sido eliminado (tipo documento: Partner).', None): ''>
Thanks for the answer.

**Comment by Arpit-SerpentCS** [comment]
solved  #187
