### ISSUE TITLE
[11.0 CE] Error when installing module created with base_module_record.

### ISSUE THREAD

**Issue by bennals** [JayVora-SerpentCS/SerpentCS_Contributions-v8#253]
In V11 CE (updated Odoo code ~two weeks old), when installing a simple module created with the wizard (Settings/Module Creation/Export Customisations as a Module) I received the error below.  The module is very simple with just three fields (below) - it is the first time I have tried to install a module created with this base_module_record module so I would not be surprised if I didn't use it correctly.

x_date_appointed | Date Appointed | date |   |   |   | Custom Field
x_name | Name | char |   |   |   | Custom Field
x_type | Officer type | char |   |   |   | Custom Field

Please advise if there is something else required in the module recording process to prevent this error.

Traceback (most recent call last):
  File "/home/odoo/odoo-server/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/odoo/odoo-server/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/home/odoo/odoo-server/odoo/addons/base/ir/ir_model.py", line 1476, in _update
    record = record.create(values)
  File "/home/odoo/odoo-server/odoo/addons/base/ir/ir_model.py", line 621, in create
    res = super(IrModelFields, self).create(vals)
  File "/home/odoo/odoo-server/odoo/models.py", line 3369, in create
    record = self.browse(self._create(old_vals))
  File "/home/odoo/odoo-server/odoo/models.py", line 3462, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/home/odoo/odoo-server/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/home/odoo/odoo-server/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: null value in column "model" violates not-null constraint
DETAIL:  Failing row contains (13453, x_date_appointed, null, null, null, null, null, Date Appointed, null, date, , t, null, f, f, f, f, null, manual, set null, [], t, null, null, null, null, null, t, 1, 2018-07-22 08:36:36.846266, 1, 2018-07-22 08:36:36.846266, null, t).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/odoo-server/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/odoo-server/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/odoo/odoo-server/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/odoo-server/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/odoo-server/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/odoo-server/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/odoo-server/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/odoo-server/addons/web/controllers/main.py", line 935, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/odoo-server/addons/web/controllers/main.py", line 923, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/odoo-server/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/odoo-server/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-43>", line 2, in button_immediate_install
  File "/home/odoo/odoo-server/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/odoo/odoo-server/odoo/addons/base/module/module.py", line 448, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/home/odoo/odoo-server/odoo/addons/base/module/module.py", line 541, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/odoo/odoo-server/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/odoo-server/odoo/modules/loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "/home/odoo/odoo-server/odoo/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/odoo/odoo-server/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/home/odoo/odoo-server/odoo/modules/loading.py", line 94, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/odoo/odoo-server/odoo/tools/convert.py", line 788, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/odoo/odoo-server/odoo/tools/convert.py", line 849, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/odoo/odoo-server/odoo/tools/convert.py", line 738, in parse
    self.parse(rec, mode)
  File "/home/odoo/odoo-server/odoo/tools/convert.py", line 748, in parse
    exc_info[2]
  File "/home/odoo/odoo-server/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/home/odoo/odoo-server/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/odoo/odoo-server/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/home/odoo/odoo-server/odoo/addons/base/ir/ir_model.py", line 1476, in _update
    record = record.create(values)
  File "/home/odoo/odoo-server/odoo/addons/base/ir/ir_model.py", line 621, in create
    res = super(IrModelFields, self).create(vals)
  File "/home/odoo/odoo-server/odoo/models.py", line 3369, in create
    record = self.browse(self._create(old_vals))
  File "/home/odoo/odoo-server/odoo/models.py", line 3462, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/home/odoo/odoo-server/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/home/odoo/odoo-server/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
odoo.tools.convert.ParseError: "null value in column "model" violates not-null constraint
DETAIL:  Failing row contains (13453, x_date_appointed, null, null, null, null, null, Date Appointed, null, date, , t, null, f, f, f, f, null, manual, set null, [], t, null, null, null, null, null, t, 1, 2018-07-22 08:36:36.846266, 1, 2018-07-22 08:36:36.846266, null, t).
" while parsing /home/odoo/custom/addons/officer_reg/officer_reg_data.xml:4, near
<record id="ir_model_fields_xdateappointed0" model="ir.model.fields">
			<field name="name">x_date_appointed</field>
			<field name="model">x_officer_register</field>
			<field eval="[(6,0,[])]" name="groups"/>
			<field name="write_uid" ref="base.user_root"/>
			<field name="create_uid" ref="base.user_root"/>
			<field name="write_date">2018-07-22 08:30:16</field>
			<field name="state">manual</field>
			<field name="create_date">2018-07-22 08:06:23</field>
			<field eval="1" name="copy"/>
			<field name="ttype">date</field>
			<field name="field_description">Date Appointed</field>
			<field model="ir.model" name="model_id" search="[('name', '=', 'Register of Officers')]"/>
			<field eval="0" name="translate"/>
			<field eval="0" name="required"/>
			<field name="domain">[]</field>
			<field eval="0" name="index"/>
			<field name="on_delete">set null</field>
			<field eval="1" name="store"/>
			<field eval="0" name="readonly"/>
			<field eval="1" name="selectable"/>
			<field eval="1" name="website_form_blacklisted"/>
		</record>

Thank you.

**Comment by JayVora-SerpentCS** [comment]
@anand-serpentcs plz check

**Comment by JayVora-SerpentCS** [comment]
#262 Closed it

**Comment by bennals** [comment]
@JayVora-SerpentCS is the code in pull request #262 ready for use?  It seems to still have issues with passing tests.

**Comment by anand-serpentcs** [comment]
@bennals ,

Thanks for reporting us a bug. We have fixed it and also we have refactored module. You can take a pull and use it.

I have attached the GIF which contains the steps for how to create a module which contains one model with some fields.
![base_module_record](https://user-images.githubusercontent.com/25679505/43766897-51706bc0-9a51-11e8-97d3-d2a1eca365a8.gif)

**Comment by bennals** [comment]
@anand-serpentcs,

That's great! Thank you for the gif as well.

**Comment by anand-serpentcs** [comment]
> @anand-serpentcs,
> 
> That's great! Thank you for the gif as well.

@bennals , You are welcome.

**Comment by bennals** [comment]
@anand-serpentcs 
Sorry to ask a question here, but I just tried using base_record_module to add a field to res.partner and struck an error.  Before I report that, can you tell me if base_record_module is capable of creating a module that adds a new field to an existing model (like res.partner), or is that function outside the scope of the module?
