### ISSUE TITLE
Publish as module

### ISSUE THREAD

**Issue by elvise** [JayVora-SerpentCS/SerpentCS_Contributions-v8#255]
if try open the "Publish as Module" get this error 
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 647, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 689, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 930, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/odoo/custom/addons/base_module_record/wizard/base_module_save.py", line 92, in default_get
    info = "Details of " + str(len(recording_data)) + " Operation(s):\n\n"
TypeError: object of type 'NoneType' has no len()

I'm using V11

**Comment by JayVora-SerpentCS** [comment]
@anand-serpentcs plz check.

**Comment by anand-serpentcs** [comment]
Hello @elvise ,

Thanks for reporting us a bug.
I have checked the features for `Publish as Module` technically.

I have found that `Publish as Module` and `Export Customizations As a Module` has same features.

Soon we will work on refactoring and we will delete `Publish as Module` menu.

The reason for throwing an error is while execute `Publish as Module`, there seems a lack of data and without data, module can't be published. As you can see while executing `Export Customizations As a Module` menu, one popup will be generated to fill details related module then the module will be created.

**Comment by elvise** [comment]
@anand-serpentcs thanks for your update, please let me know when the module is updated.

**Comment by anand-serpentcs** [comment]
> @anand-serpentcs thanks for your update, please let me know when the module is updated.

@elvise ,
the module is updated. Just take a latest pull.
