### ISSUE TITLE
web_one2many_kanban 8 series is fine. But 9 series is not working.

### ISSUE THREAD

**Issue by shihas1991** [JayVora-SerpentCS/SerpentCS_Contributions-v8#30]
Showing this error when adding one2many in kanban view

Uncaught TypeError: Cannot read property 'append' of undefined
http://localhost:8069/web_one2many_kanban/static/src/js/web_one2many_kanban.js:339
Traceback:
TypeError: Cannot read property 'append' of undefined
    at Object.<anonymous> (http://localhost:8069/web_one2many_kanban/static/src/js/web_one2many_kanban.js:339:35)
    at Object.<anonymous> (http://localhost:8069/web/static/lib/jquery/jquery.js:3276:89)
    at jQuery.Callbacks.fire (http://localhost:8069/web/static/lib/jquery/jquery.js:3119:58)
    at Object.jQuery.Callbacks.self.fireWith [as resolveWith](http://localhost:8069/web/static/lib/jquery/jquery.js:3231:49)
    at Object.<anonymous> (http://localhost:8069/web/static/lib/jquery/jquery.js:3283:104)
    at jQuery.Callbacks.fire (http://localhost:8069/web/static/lib/jquery/jquery.js:3119:58)
    at Object.jQuery.Callbacks.self.fireWith [as resolveWith](http://localhost:8069/web/static/lib/jquery/jquery.js:3231:49)
    at Object.jQuery.extend.Deferred.jQuery.each.deferred.(anonymous function) (http://localhost:8069/web/static/lib/jquery/jquery.js:3321:62)
    at jQuery.Callbacks.fire (http://localhost:8069/web/static/lib/jquery/jquery.js:3119:58)
    at Object.jQuery.Callbacks.self.fireWith [as resolveWith](http://localhost:8069/web/static/lib/jquery/jquery.js:3231:49)

**Comment by JayVora-SerpentCS** [comment]
Thanks for reporting, will check it asap.

**Comment by ghost** [comment]
@shihas1991 

Hope you are fine.

Issue is fixed in this commit https://github.com/JayVora-SerpentCS/SerpentCS_Contributions-v8/commit/aaaae5eb8e3605baf1ab2fcac5c47e592f8403bb

Can you please check ?

Waiting for your feedback.

Thanks.

**Comment by shihas1991** [comment]
@MeetSCS 
I have checked with your last commit. Working fine. Good work

Thanks
