### ISSUE TITLE
Base_Synchro view error Odoo 12

### ISSUE THREAD

**Issue by peseotni** [JayVora-SerpentCS/SerpentCS_Contributions-v8#303]
I get the following error when I want to install this modul: 
`Odoo Server Error
Traceback (most recent call last):
  File "/opt/odooalina/odoo/tools/convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odooalina/odoo/tools/convert.py", line 662, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/opt/odooalina/odoo/models.py", line 3805, in _load_records
    records = self.create([data['values'] for data in to_create])
  File "<decorator-gen-32>", line 2, in create
  File "/opt/odooalina/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/opt/odooalina/odoo/addons/base/models/ir_ui_view.py", line 425, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/opt/odooalina/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/opt/odooalina/odoo/models.py", line 3542, in create
    fields[0].determine_inverse(batch_recs)
  File "/opt/odooalina/odoo/fields.py", line 1094, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/odooalina/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/opt/odooalina/addons/website/models/ir_ui_view.py", line 41, in write
    return super(View, self).write(vals)
  File "/opt/odooalina/odoo/addons/base/models/ir_ui_view.py", line 441, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/odooalina/odoo/models.py", line 3259, in write
    self._write(store_vals)
  File "/opt/odooalina/odoo/models.py", line 3403, in _write
    self._validate_fields(vals)
  File "/opt/odooalina/odoo/models.py", line 1102, in _validate_fields
    check(self)
  File "/opt/odooalina/odoo/addons/base/models/ir_ui_view.py", line 360, in _check_xml
    raise ValidationError(_('Invalid view %s definition in %s') % (view.name, view.arch_fs))
odoo.exceptions.ValidationError: ('Invalid view Base Synchronization definition in base_synchro/wizard/base_synchro_view.xml', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odooalina/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odooalina/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odooalina/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odooalina/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odooalina/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odooalina/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odooalina/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odooalina/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/opt/odooalina/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/opt/odooalina/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odooalina/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odooalina/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/opt/odooalina/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "/opt/odooalina/odoo/addons/base/models/ir_module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odooalina/odoo/addons/base/models/ir_module.py", line 442, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odooalina/odoo/addons/base/models/ir_module.py", line 535, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odooalina/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odooalina/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/opt/odooalina/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odooalina/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/opt/odooalina/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odooalina/odoo/tools/convert.py", line 801, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odooalina/odoo/tools/convert.py", line 864, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odooalina/odoo/tools/convert.py", line 763, in parse
    exc_info[2]
  File "/opt/odooalina/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/opt/odooalina/odoo/tools/convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odooalina/odoo/tools/convert.py", line 662, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/opt/odooalina/odoo/models.py", line 3805, in _load_records
    records = self.create([data['values'] for data in to_create])
  File "<decorator-gen-32>", line 2, in create
  File "/opt/odooalina/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/opt/odooalina/odoo/addons/base/models/ir_ui_view.py", line 425, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/opt/odooalina/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/opt/odooalina/odoo/models.py", line 3542, in create
    fields[0].determine_inverse(batch_recs)
  File "/opt/odooalina/odoo/fields.py", line 1094, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/odooalina/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/opt/odooalina/addons/website/models/ir_ui_view.py", line 41, in write
    return super(View, self).write(vals)
  File "/opt/odooalina/odoo/addons/base/models/ir_ui_view.py", line 441, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/odooalina/odoo/models.py", line 3259, in write
    self._write(store_vals)
  File "/opt/odooalina/odoo/models.py", line 3403, in _write
    self._validate_fields(vals)
  File "/opt/odooalina/odoo/models.py", line 1102, in _validate_fields
    check(self)
  File "/opt/odooalina/odoo/addons/base/models/ir_ui_view.py", line 360, in _check_xml
    raise ValidationError(_('Invalid view %s definition in %s') % (view.name, view.arch_fs))
odoo.tools.convert.ParseError: "Invalid view Base Synchronization definition in base_synchro/wizard/base_synchro_view.xml
None" while parsing /opt/addons/base_synchro/wizard/base_synchro_view.xml:35, near
`<record id="view_base_synchro_finish" model="ir.ui.view">`
`        <field name="name">Base Synchronization</field>`
`        <field name="model">base.synchro</field>`
`        <field name="arch" type="xml">`
`            <form string="Synchronization Completed!">`
`                <label string="The synchronisation has been started. You will receive a request when it's done."/>`
`               <footer>`
`                    <button string="Cancel" class="oe_link" special="cancel"/>`
`                </footer>`
`            </form>`
`        </field>`
`    </record>`

**Comment by JayVora-SerpentCS** [comment]
Its the Work in progress.

**Comment by JayVora-SerpentCS** [comment]
#307 Closed this.
