### ISSUE TITLE
v12.0 Website Product Multi-Image Zoom not installing

### ISSUE THREAD

**Issue by ayobello** [JayVora-SerpentCS/SerpentCS_Contributions-v8#339]
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo12/odoo12-server/odoo/models.py", line 1108, in _validate_fields
    check(self)
  File "/odoo12/odoo12-server/odoo/addons/base/models/ir_ui_view.py", line 345, in _check_xml
    view_def = view.read_combined(['arch'])
  File "/odoo12/odoo12-server/odoo/addons/base/models/ir_ui_view.py", line 784, in read_combined
    arch = self.apply_view_inheritance(arch_tree, root.id, self.model)
  File "/odoo12/odoo12-server/odoo/addons/base/models/ir_ui_view.py", line 732, in apply_view_inheritance
    source = self.apply_inheritance_specs(source, specs_tree, view_id)
  File "/odoo12/odoo12-server/odoo/addons/base/models/ir_ui_view.py", line 710, in apply_inheritance_specs
    self.raise_view_error(_("Element '%s' cannot be located in parent view") % tag, inherit_id)
  File "/odoo12/odoo12-server/odoo/addons/base/models/ir_ui_view.py", line 548, in raise_view_error
    raise ValueError(message)
ValueError: Element '<xpath expr="//section[@id='product_detail']/div[@class='row']/div[@class='col-sm-7']">' cannot be located in parent view

Error context:
View `product_extended`
[view_id: 1586, xml_id: n/a, model: n/a, parent_id: 1028]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo12/odoo12-server/odoo/tools/convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/odoo12/odoo12-server/odoo/tools/convert.py", line 735, in _tag_template
    return self._tag_record(record, data_node)
  File "/odoo12/odoo12-server/odoo/tools/convert.py", line 662, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/odoo12/odoo12-server/odoo/models.py", line 3838, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/odoo12/odoo12-server/addons/website/models/ir_ui_view.py", line 128, in _load_records_create
    records = super(View, self)._load_records_create(values)
  File "/odoo12/odoo12-server/odoo/models.py", line 3752, in _load_records_create
    return self.create(values)
  File "<decorator-gen-32>", line 2, in create
  File "/odoo12/odoo12-server/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/odoo12/odoo12-server/odoo/addons/base/models/ir_ui_view.py", line 428, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/odoo12/odoo12-server/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/odoo12/odoo12-server/odoo/models.py", line 3569, in create
    fields[0].determine_inverse(batch_recs)
  File "/odoo12/odoo12-server/odoo/fields.py", line 1110, in determine_inverse
    getattr(records, self.inverse)()
  File "/odoo12/odoo12-server/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/odoo12/odoo12-server/addons/website/models/ir_ui_view.py", line 41, in write
    return super(View, self).write(vals)
  File "/odoo12/odoo12-server/odoo/addons/base/models/ir_ui_view.py", line 444, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/odoo12/odoo12-server/odoo/models.py", line 3284, in write
    self._write(store_vals)
  File "/odoo12/odoo12-server/odoo/models.py", line 3430, in _write
    self._validate_fields(vals)
  File "/odoo12/odoo12-server/odoo/models.py", line 1112, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Error while validating constraint\n\nElement \'<xpath expr="//section[@id=\'product_detail\']/div[@class=\'row\']/div[@class=\'col-sm-7\']">\' cannot be located in parent view\n\nError context:\nView `product_extended`\n[view_id: 1586, xml_id: n/a, model: n/a, parent_id: 1028]', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo12/odoo12-server/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo12/odoo12-server/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo12/odoo12-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo12/odoo12-server/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/odoo12/odoo12-server/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo12/odoo12-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo12/odoo12-server/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo12/odoo12-server/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/odoo12/odoo12-server/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/odoo12/odoo12-server/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo12/odoo12-server/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo12/odoo12-server/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/odoo12/odoo12-server/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "/odoo12/odoo12-server/odoo/addons/base/models/ir_module.py", line 73, in check_and_log
    return method(self, *args, **kwargs)
  File "/odoo12/odoo12-server/odoo/addons/base/models/ir_module.py", line 444, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/odoo12/odoo12-server/odoo/addons/base/models/ir_module.py", line 552, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/odoo12/odoo12-server/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo12/odoo12-server/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/odoo12/odoo12-server/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/odoo12/odoo12-server/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/odoo12/odoo12-server/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/odoo12/odoo12-server/odoo/tools/convert.py", line 801, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/odoo12/odoo12-server/odoo/tools/convert.py", line 864, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/odoo12/odoo12-server/odoo/tools/convert.py", line 763, in parse
    exc_info[2]
  File "/odoo12/odoo12-server/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/odoo12/odoo12-server/odoo/tools/convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/odoo12/odoo12-server/odoo/tools/convert.py", line 735, in _tag_template
    return self._tag_record(record, data_node)
  File "/odoo12/odoo12-server/odoo/tools/convert.py", line 662, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/odoo12/odoo12-server/odoo/models.py", line 3838, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/odoo12/odoo12-server/addons/website/models/ir_ui_view.py", line 128, in _load_records_create
    records = super(View, self)._load_records_create(values)
  File "/odoo12/odoo12-server/odoo/models.py", line 3752, in _load_records_create
    return self.create(values)
  File "<decorator-gen-32>", line 2, in create
  File "/odoo12/odoo12-server/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/odoo12/odoo12-server/odoo/addons/base/models/ir_ui_view.py", line 428, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/odoo12/odoo12-server/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/odoo12/odoo12-server/odoo/models.py", line 3569, in create
    fields[0].determine_inverse(batch_recs)
  File "/odoo12/odoo12-server/odoo/fields.py", line 1110, in determine_inverse
    getattr(records, self.inverse)()
  File "/odoo12/odoo12-server/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/odoo12/odoo12-server/addons/website/models/ir_ui_view.py", line 41, in write
    return super(View, self).write(vals)
  File "/odoo12/odoo12-server/odoo/addons/base/models/ir_ui_view.py", line 444, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/odoo12/odoo12-server/odoo/models.py", line 3284, in write
    self._write(store_vals)
  File "/odoo12/odoo12-server/odoo/models.py", line 3430, in _write
    self._validate_fields(vals)
  File "/odoo12/odoo12-server/odoo/models.py", line 1112, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Error while validating constraint

Element '<xpath expr="//section[@id='product_detail']/div[@class='row']/div[@class='col-sm-7']">' cannot be located in parent view

Error context:
View `product_extended`
[view_id: 1586, xml_id: n/a, model: n/a, parent_id: 1028]
None" while parsing None:27, near
<data name="product_extended" inherit_id="website_sale.product">
        <xpath expr="//section[@id='product_detail']/div[@class='row']/div[@class='col-sm-7']" position="replace">
            <input type="hidden" id="variant_img_display" t-att-value="product.variant_bool"/>
            <input type="hidden" id="product_img_display" t-att-value="product.id"/>
            <div class="col-sm-7 col-md-7 col-lg-7">
                
                <div class="image_bigsize">
                    <div id="ex1" onclick="full_img(this)">
                        <span itemprop="image" t-field="product.image" t-field-options="{&quot;widget&quot;: &quot;image&quot;, &quot;class&quot;: &quot;img_set&quot;}"/>
                    </div>
                </div>
                
                <div class="modal fade" tabindex="-1" role="dialog" id="img_modal" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="padding:5px;margin-bottom:-8%;color:red;">x
                            </button>
                            <img class="img img-responsive" id="modal_img"/>
                        </div>
                    </div>
                </div>
                
                <div id="thumb_img_add">
                    <div id="carousel-custom" class="carousel slide">
                        
                        <ol class="carousel-indicators">
                            <li>
                                <img onclick="pro_img_click(this)" itemprop="image" class="image_thumb img-responsive" t-att-src="'data:image/jpeg;base64,%s' %product.image"/>
                            </li>
                            <t t-foreach="product.images" t-as="i">
                                <li>
                                    <img onclick="pro_img_click(this)" class="image_thumb img-responsive" t-att-src="'data:image/jpeg;base64,%s' %i.image"/>
                                </li>
                            </t>
                        </ol>
                    </div>
                </div>
                <hr/>
            </div>
        </xpath>
    </data>

**Comment by JayVora-SerpentCS** [comment]
What 3rd party modules do you have along with this module?
cc @swapnesh-serpentcs

**Comment by ayobello** [comment]
Hi @JayVora-SerpentCS, apologies for late response, I've being up and about in recent days. As for the 3rd party modules installed, I have a bunch of them on this particular instant; though they are all from reputable sources but I will try on a fresh install and revert. In the mean time, did you happen to spot anything unusual in the error code I posted?

Thanks

**Comment by JayVora-SerpentCS** [comment]
We did nt get it, so closing for now.
Product model usually gets customised by many modules, so its highly possible that 2 modules conflict.
