### ISSUE TITLE
Error in Synchronize

### ISSUE THREAD

**Issue by asiamatrix** [JayVora-SerpentCS/SerpentCS_Contributions-v8#364]
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/custom/addons/base_synchro/wizard/base_synchro.py", line 292, in upload_download_multi_thread
    threading.Thread(target=self.upload_download())
  File "/odoo/custom/addons/base_synchro/wizard/base_synchro.py", line 255, in upload_download
    self.synchronize(server, obj_rec)
  File "/odoo/custom/addons/base_synchro/wizard/base_synchro.py", line 85, in synchronize
    get_ids(model_obj, dt, eval(object.domain), {'action': 'd'})
  File "/odoo/custom/addons/base_synchro/wizard/base_synchro.py", line 32, in <lambda>
    *args)
  File "/usr/lib/python3.6/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.6/xmlrpc/client.py", line 1452, in __request
    verbose=self.__verbose
  File "/usr/lib/python3.6/xmlrpc/client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.6/xmlrpc/client.py", line 1170, in single_request
    return self.parse_response(resp)
  File "/usr/lib/python3.6/xmlrpc/client.py", line 1342, in parse_response
    return u.close()
  File "/usr/lib/python3.6/xmlrpc/client.py", line 656, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault write_date: 'Traceback (most recent call last):\n  File "/odoo/odoo-server/odoo/addons/base/controllers/rpc.py", line 54, in xmlrpc_1\n    response = self._xmlrpc(service)\n  File "/odoo/odoo-server/odoo/addons/base/controllers/rpc.py", line 43, in _xmlrpc\n    result = dispatch_rpc(service, method, params)\n  File "/odoo/odoo-server/odoo/http.py", line 120, in dispatch_rpc\n    result = dispatch(method, params)\n  File "/odoo/odoo-server/odoo/service/model.py", line 39, in dispatch\n    res = fn(db, uid, *params)\n  File "/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper\n    return f(dbname, *args, **kwargs)\n  File "/odoo/odoo-server/odoo/service/model.py", line 160, in execute\n    res = execute_cr(cr, uid, obj, method, *args, **kw)\n  File "/odoo/odoo-server/odoo/service/model.py", line 149, in execute_cr\n    return odoo.api.call_kw(recs, method, args, kw)\n  File "/odoo/odoo-server/odoo/api.py", line 745, in call_kw\n    return _call_kw_model(method, model, args, kwargs)\n  File "/odoo/odoo-server/odoo/api.py", line 718, in _call_kw_model\n    result = method(recs, *args, **kwargs)\n  File "/odoo/custom/addons/base_synchro/models/base_synchro_obj.py", line 117, in get_ids\n    result.append((r[\'write_date\'] or r[\'create_date\'], r[\'id\'],\nKeyError: \'write_date\'\n'>

**Comment by bansari-serpentcs** [comment]
Hello @asiamatrix 
On which version you are getting this Issue ?
(also We fixed same kind of issue last week, it would be great if you can update the code and try again)

**Comment by asiamatrix** [comment]
Odoo 12 CE.

**Comment by bansari-serpentcs** [comment]
Oh, Fixes for the 12 CE is under testing and will be merged soon.
For now you can test this from https://github.com/bansari-serpentcs/SerpentCS_Contributions/tree/12.0

(PR is https://github.com/JayVora-SerpentCS/SerpentCS_Contributions/pull/365)

**Comment by kit9** [comment]
Please help..

Eror!:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base_synchro/wizard/base_synchro.py", line 292, in upload_download_multi_thread
    threading.Thread(target=self.upload_download())
  File "/usr/lib/python3/dist-packages/odoo/addons/base_synchro/wizard/base_synchro.py", line 255, in upload_download
    self.synchronize(server, obj_rec)
  File "/usr/lib/python3/dist-packages/odoo/addons/base_synchro/wizard/base_synchro.py", line 74, in synchronize
    module = pool1.get('ir.module.module')
  File "/usr/lib/python3/dist-packages/odoo/addons/base_synchro/wizard/base_synchro.py", line 42, in get
    return RPCProxyOne(self.server, ressource)
  File "/usr/lib/python3/dist-packages/odoo/addons/base_synchro/wizard/base_synchro.py", line 21, in __init__
    self.uid = rpc.login(server.server_db, server.login, server.password)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1092, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1432, in __request
    verbose=self.__verbose
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1134, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1146, in single_request
    http_conn = self.send_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1259, in send_request
    self.send_content(connection, request_body)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1289, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 711, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 702, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

**Comment by JayVora-SerpentCS** [comment]
check with latest source now please.
