### ISSUE TITLE
Client Side Error After Update of PR408 in web_groupby_expand

### ISSUE THREAD

**Issue by BT-mfasola** [JayVora-SerpentCS/SerpentCS_Contributions-v8#414]
After updating to the latest version of web_groupby_expand merged with #408 the following error occurs only on mobile browsers (tested on chrome/android):
`Error:
Uncaught TypeError: Cannot read property 'hide' of undefined

https://testus.odoo.com/web/content/10969-e08e713/web.assets_backend.js:4023
Traceback:
TypeError: Cannot read property 'hide' of undefined
    at Class._renderSwitchButtons (https://testus.odoo.com/web/content/10969-e08e713/web.assets_backend.js:4023:43)
    at Class._renderSwitchButtons (https://testus.odoo.com/web/content/10580-73493bf/web.assets_common.js:3541:371)
    at Class._renderControlPanelElements (https://testus.odoo.com/web/content/10969-e08e713/web.assets_backend.js:1304:390)
    at Class.start (https://testus.odoo.com/web/content/10969-e08e713/web.assets_backend.js:1296:1462)
    at Class.prototype.<computed> [as start] (https://testus.odoo.com/web/content/10580-73493bf/web.assets_common.js:3538:488)
    at Class.start (https://testus.odoo.com/web/content/10969-e08e713/web.assets_backend.js:1561:1042)
    at Class.prototype.<computed> [as start] (https://testus.odoo.com/web/content/10580-73493bf/web.assets_common.js:3538:488)
    at https://testus.odoo.com/web/content/10580-73493bf/web.assets_common.js:3684:52
    at https://testus.odoo.com/web/content/10580-73493bf/web.assets_common.js:802:681
    at fire (https://testus.odoo.com/web/content/10580-73493bf/web.assets_common.js:796:299)`

**Comment by JayVora-SerpentCS** [comment]
@nikitavaghela

**Comment by BT-mfasola** [comment]
thanks!
