### ISSUE TITLE
Error on date format when synchronizing

### ISSUE THREAD

**Issue by fabienlege** [JayVora-SerpentCS/SerpentCS_Contributions-v8#430]
After my first issue (#426) you've patched, I retry to synchronize two fresh installed odoo 13 installations.

Installation and server configuration seem to work correctly. but when I try to launch Config > Synchronization > Synchronize Objects, i've this error :
```
Erreur:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 910, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1324, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1312, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base_synchro/wizard/base_synchro.py", line 290, in upload_download_multi_thread
    threading.Thread(target=self.upload_download())
  File "/usr/lib/python3/dist-packages/odoo/addons/base_synchro/wizard/base_synchro.py", line 284, in upload_download
    'body': summary,
  File "<decorator-gen-3>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 335, in _model_create_multi
    return create(self, [arg])
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3733, in create
    records = self._create(data_list)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3850, in _create
    cache_value = field.convert_to_cache(value, record)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1810, in convert_to_cache
    return self.to_datetime(value)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1790, in to_datetime
    return datetime.strptime(value, DATETIME_FORMAT[:len(value)-2])
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '2020-03-19, 10:32:37' does not match format '%Y-%m-%d %H:%M:%S'
```

my Odoo instances are installed on two fresh created vps ubuntu server 18.04

**Comment by JayVora-SerpentCS** [comment]
@swapnesh-serpentcs plz check.

**Comment by Swapnesh-SerpentCS** [comment]
Fixed in https://github.com/JayVora-SerpentCS/SerpentCS_Contributions/pull/432
