### ISSUE TITLE
Web Security Dialog v13.0: Traceback/Warning message on Adding correct password.

### ISSUE THREAD

**Issue by poonam-serpentcs** [JayVora-SerpentCS/SerpentCS_Contributions-v8#490]
https://prnt.sc/tn1q8p

https://prnt.sc/tn1qf6

**Comment by hpatelserpentcs** [comment]
@poonam-serpentcs

Please check your button option attribute, it did not throw any Traceback/Warning message.

**Comment by poonam-serpentcs** [comment]
- Created a new Database
- Installed Web Security Dialog and CRM Module
- Edited form view and added Option confirm="message" options='{"security":"security_field"}'


Still getting same Error

```
2020-08-17 05:08:09,556 32248 ERROR ent_web_security_13 odoo.http: Exception during JSON request handling. 
Traceback (most recent call last):
  File "/home/serpentcs/WorkSpace/13.0/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/serpentcs/WorkSpace/13.0/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/serpentcs/WorkSpace/13.0/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/home/serpentcs/WorkSpace/13.0/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/home/serpentcs/WorkSpace/13.0/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/serpentcs/WorkSpace/13.0/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/serpentcs/WorkSpace/13.0/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/serpentcs/WorkSpace/13.0/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/home/serpentcs/WorkSpace/13.0/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/serpentcs/WorkSpace/13.0/addons/web/controllers/main.py", line 1322, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/serpentcs/WorkSpace/13.0/addons/web/controllers/main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/serpentcs/WorkSpace/13.0/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/serpentcs/WorkSpace/13.0/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/serpentcs/WorkSpace/wfh_projects/web_security/web_security_dialog/models/res_company.py", line 17, in check_security
    [fields])
  File "/home/serpentcs/WorkSpace/13.0/odoo/models.py", line 4858, in search_read
    result = records.read(fields)
  File "/home/serpentcs/WorkSpace/13.0/odoo/models.py", line 2896, in read
    raise ValueError("Invalid field %r on model %r" % (name, self._name))
ValueError: Invalid field 'security_field' on model 'res.company'
2020-08-17 05:08:09,636 32248 INFO ent_web_security_13 werkzeug: 127.0.0.1 - - [17/Aug/2020 05:08:09] "POST /web/dataset/call_kw/res.company/check_security HTTP/1.1" 200 - 3 0.001 0.085
2020-08-17 05:08:09,682 32248 INFO ? werkzeug: 127.0.0.1 - - [17/Aug/2020 05:08:09] "GET /web/static/src/xml/crash_manager.xml?debug=1597640889673 HTTP/1.1" 200 -
```




This is the code of a button

`<button name="action_set_won_rainbowman" confirm="Enter Password" options='{"security":"security_field"}'  string="Mark Won" type="object" class="oe_highlight" attrs="{'invisible': ['|','|', ('active','=',False), ('probability', '=', 100), ('type', '=', 'lead')]}"/>`

**Comment by poonam-serpentcs** [comment]
Discussed with @hpatelserpentcs It is due to the wrong field name given in Option.
`options='{"security":"security_key"}'`  works fine.

We will correct this in the index file.
