### ISSUE TITLE
Label 9

### ISSUE THREAD

**Issue by mikes-techzone** [JayVora-SerpentCS/SerpentCS_Contributions-v8#51]
Hi, i have this error on install (windows odoo 9) 

Odoo Server Error
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 9.0-20160525\server.\openerp\http.py", line 643, in _handle_exception
  File "C:\Program Files (x86)\Odoo 9.0-20160525\server.\openerp\http.py", line 680, in dispatch
  File "C:\Program Files (x86)\Odoo 9.0-20160525\server.\openerp\http.py", line 316, in _call_function
  File "C:\Program Files (x86)\Odoo 9.0-20160525\server.\openerp\service\model.py", line 118, in wrapper
  File "C:\Program Files (x86)\Odoo 9.0-20160525\server.\openerp\http.py", line 309, in checked_call
  File "C:\Program Files (x86)\Odoo 9.0-20160525\server.\openerp\http.py", line 959, in __call__
  File "C:\Program Files (x86)\Odoo 9.0-20160525\server.\openerp\http.py", line 509, in response_wrap
  File "C:\Program Files (x86)\Odoo 9.0-20160525\server\openerp\addons\web\controllers\main.py", line 900, in call_button
  File "C:\Program Files (x86)\Odoo 9.0-20160525\server\openerp\addons\web\controllers\main.py", line 888, in _call_kw
  File "C:\Program Files (x86)\Odoo 9.0-20160525\server.\openerp\api.py", line 250, in wrapper
  File "C:\Program Files (x86)\Odoo 9.0-20160525\server\openerp\addons\base\module\module.py", line 459, in button_immediate_install
  File "C:\Program Files (x86)\Odoo 9.0-20160525\server.\openerp\api.py", line 250, in wrapper
  File "C:\Program Files (x86)\Odoo 9.0-20160525\server\openerp\addons\base\module\module.py", line 533, in _button_immediate_function
  File "C:\Program Files (x86)\Odoo 9.0-20160525\server.\openerp\modules\registry.py", line 386, in new
  File "C:\Program Files (x86)\Odoo 9.0-20160525\server.\openerp\modules\loading.py", line 338, in load_modules
  File "C:\Program Files (x86)\Odoo 9.0-20160525\server.\openerp\modules\loading.py", line 237, in load_marked_modules
  File "C:\Program Files (x86)\Odoo 9.0-20160525\server.\openerp\modules\loading.py", line 123, in load_module_graph
  File "C:\Program Files (x86)\Odoo 9.0-20160525\server.\openerp\modules\module.py", line 324, in load_openerp_module
  File "C:\Program Files (x86)\Odoo 9.0-20160525\server.\openerp\modules\module.py", line 61, in load_module
  File "C:\Program Files (x86)\Odoo 9.0-20160525\server\openerp\addons\label__init__.py", line 6, in <module>
  File "C:\Program Files (x86)\Odoo 9.0-20160525\server\openerp\addons\label\report__init__.py", line 3, in <module>
  File "C:\Program Files (x86)\Odoo 9.0-20160525\server\openerp\addons\label\report\dynamic_label.py", line 16, in <module>
  File "C:\Program Files (x86)\Odoo 9.0-20160525\server.\cairosvg__init__.py", line 27, in <module>
  File "C:\Program Files (x86)\Odoo 9.0-20160525\server.\cairosvg\surface__init__.py", line 30, in <module>
  File "C:\Program Files (x86)\Odoo 9.0-20160525\server.\cairo__init__.py", line 1, in <module>
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.
Ok

**Comment by JayVora-SerpentCS** [comment]
Hello, you need to have a windows compatible cairo lib.
