### ISSUE TITLE
sales_report_product_image installation error

### ISSUE THREAD

**Issue by pascalpci** [JayVora-SerpentCS/SerpentCS_Contributions-v8#59]
Hi, 
I got the latest version available on the git with the comment "[FIX] Fixed the issue of xpath, sales report errors during module ins…"
when i try to install sales_report_product_image, i have this error:
what can i do to solve it ?
thanks.

```
return new_api(self, *args, **kwargs)
```

  File "/opt/odoo/odoo/openerp/models.py", line 4157, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 490, in new_api
    result = method(self._model, cr, uid, _args, *_old_kwargs)
  File "/opt/odoo/odoo/openerp/models.py", line 4354, in _create
    recs._validate_fields(vals)
  File "/opt/odoo/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/models.py", line 1271, in _validate_fields
    raise ValidationError('\n'.join(errors))
ParseError: "Invalid view definition

D\xe9tails de l'erreur :
L'\xe9l\xe9ment '<xpath expr="//table/tbody[@class='sale_tbody']/t/tr/td[1]">' ne peut \xeatre localis\xe9 dans la vue parente

Contexte de l'erreur :
Vue `report_saleorder_document_inherit`
[view_id: 1378, xml_id: n/a, model: n/a, parent_id: 498]
None" while parsing None:4, near
<data inherit_id="sale.report_saleorder_document">
         <xpath expr="//table[@class='table table-condensed']/thead/tr/th[1]" position="before">
             <t t-if="doc.print_image and doc.image_sizes in ('image', 'image_medium', 'image_small') ">
                 <th>
                    Product Image
                </th>
             </t>
        </xpath>
        <xpath expr="//table/tbody[@class='sale_tbody']/t/tr/td[1]" position="before">
            <t t-if="doc.image_sizes == 'image' and doc.print_image ">
                <td>
                    <span t-field="l.product_id.image" t-field-options="{&quot;widget&quot;: &quot;image&quot;, &quot;class&quot;: &quot;img-rounded&quot;}"/>
                </td>
            </t>
            <t t-if="doc.image_sizes == 'image_medium' and doc.print_image">
                <td>
                    <span t-field="l.product_id.image_medium" t-field-options="{&quot;widget&quot;: &quot;image&quot;, &quot;class&quot;: &quot;img-rounded&quot;}"/>
                </td>
            </t>
            <t t-if="doc.image_sizes == 'image_small' and doc.print_image ">
                <td>
                    <span t-field="l.product_id.image_small" t-field-options="{&quot;widget&quot;: &quot;image&quot;, &quot;class&quot;: &quot;img-rounded&quot;}"/>
                </td>
            </t>
        </xpath>
    </data>

**Comment by JayVora-SerpentCS** [comment]
It has been fixed with latest version.
Thanks.

**Comment by undigo** [comment]
-----------------
odoo Version 9.0c-20160620 (Community Edition)
Linux ubuntu 3.13.0-101-generic #148-Ubuntu SMP Thu Oct 20 22:08:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux from bitnami Stack
------------
STEP 1 : I try to install your V9 branch for addon sales_report_product_image 

I've got on openerp_server.log :
Odoo Server Error
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/http.py", line 319, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/http.py", line 312, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/http.py", line 962, in __call__
    return self.method(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/addons/web/controllers/main.py", line 901, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/addons/web/controllers/main.py", line 889, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/addons/base/module/module.py", line 459, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/addons/base/module/module.py", line 533, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/modules/loading.py", line 338, in load_modules
    loaded_modules, update_module)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/tools/convert.py", line 851, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/tools/convert.py", line 938, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/tools/convert.py", line 804, in parse
    self._tags[rec.tag](self.cr, rec, de, mode=mode)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/tools/convert.py", line 777, in _tag_template
    return self._tag_record(cr, record, data_node)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/tools/convert.py", line 708, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/addons/base/ir/ir_model.py", line 1143, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/addons/base/ir/ir_ui_view.py", line 353, in create
    context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/api.py", line 354, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/models.py", line 4151, in create
    record = self.browse(self._create(old_vals))
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/api.py", line 490, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/models.py", line 4342, in _create
    recs._validate_fields(vals)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/models.py", line 1271, in _validate_fields
    raise ValidationError('\n'.join(errors))
ParseError: "Invalid view definition

D\xe9tails de l'erreur :
L'\xe9l\xe9ment '<xpath expr="//table/tbody[@class='sale_tbody']/t/tr/td[1]">' ne peut \xeatre localis\xe9 dans la vue parente

Contexte de l'erreur :
Vue `report_saleorder_document_inherit`
[view_id: 1777, xml_id: n/a, model: n/a, parent_id: 735]
None" while parsing None:4, near
<data inherit_id="sale.report_saleorder_document">
         <xpath expr="//table[@class='table table-condensed']/thead/tr/th[1]" position="before">
             <t t-if="doc.print_image and doc.image_sizes in ('image', 'image_medium', 'image_small') ">
                 <th>
                    Product Image
                </th>
             </t>
        </xpath>
        <xpath expr="//table/tbody[@class='sale_tbody']/t/tr/td[1]" position="before">
            <t t-if="doc.image_sizes == 'image' and doc.print_image ">
                <td>
                    <span t-field="l.product_id.image" t-field-options="{&quot;widget&quot;: &quot;image&quot;, &quot;class&quot;: &quot;img-rounded&quot;}"/>
                </td>
            </t>
            <t t-if="doc.image_sizes == 'image_medium' and doc.print_image">
                <td>
                    <span t-field="l.product_id.image_medium" t-field-options="{&quot;widget&quot;: &quot;image&quot;, &quot;class&quot;: &quot;img-rounded&quot;}"/>
                </td>
            </t>
            <t t-if="doc.image_sizes == 'image_small' and doc.print_image ">
                <td>
                    <span t-field="l.product_id.image_small" t-field-options="{&quot;widget&quot;: &quot;image&quot;, &quot;class&quot;: &quot;img-rounded&quot;}"/>
                </td>
            </t>
        </xpath>
    </data>

STEP 2 : I  try to install V10 branch
no error just cancel button wait on application module

and on error log : 
2017-02-02 22:55:09,084 10634 INFO bitnami_openerp openerp.modules.loading: 157 modules loaded in 0.21s, 0 queries
2017-02-02 22:55:09,086 10634 WARNING bitnami_openerp openerp.modules.graph: **module sales_report_product_image: not installable, skipped**
2017-02-02 22:55:09,095 10634 WARNING bitnami_openerp openerp.modules.graph: Some modules were not loaded.

thanks for your assistance.
Regards,

**Comment by JayVora-SerpentCS** [comment]
Can you please check with latest source?
