### ISSUE TITLE
Sync Error

### ISSUE THREAD

**Issue by kyawsoekhaing** [JayVora-SerpentCS/SerpentCS_Contributions-v8#60]
I am geting the following error when I try following steps from the following links
http://toolkt.com/site/openerp-base_synchrosynchronization/

I am using Odoo 9 and using the following addon "https://www.odoo.com/apps/modules/9.0/base_synchro" on Windows 7 64bit.
Pls help

Odoo Server Error
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 9.0-20160830\server.\openerp\http.py", line 648, in _handle_exception
  File "C:\Program Files (x86)\Odoo 9.0-20160830\server.\openerp\http.py", line 685, in dispatch
  File "C:\Program Files (x86)\Odoo 9.0-20160830\server.\openerp\http.py", line 321, in _call_function
  File "C:\Program Files (x86)\Odoo 9.0-20160830\server.\openerp\service\model.py", line 118, in wrapper
  File "C:\Program Files (x86)\Odoo 9.0-20160830\server.\openerp\http.py", line 314, in checked_call
  File "C:\Program Files (x86)\Odoo 9.0-20160830\server.\openerp\http.py", line 964, in __call__
  File "C:\Program Files (x86)\Odoo 9.0-20160830\server.\openerp\http.py", line 514, in response_wrap
  File "C:\Program Files (x86)\Odoo 9.0-20160830\server\openerp\addons\web\controllers\main.py", line 892, in call_button
  File "C:\Program Files (x86)\Odoo 9.0-20160830\server\openerp\addons\web\controllers\main.py", line 880, in _call_kw
  File "C:\Program Files (x86)\Odoo 9.0-20160830\server.\openerp\api.py", line 250, in wrapper
  File "C:\Program Files (x86)\Odoo 9.0-20160830\server.\openerp\api.py", line 381, in old_api
  File "C:\Program Files (x86)\Odoo 9.0-20160830\server\openerp\addons\base_synchro\wizard\base_synchro.py", line 268, in upload_download_multi_thread
  File "C:\Program Files (x86)\Odoo 9.0-20160830\server.\openerp\api.py", line 248, in wrapper
  File "C:\Program Files (x86)\Odoo 9.0-20160830\server\openerp\addons\base_synchro\wizard\base_synchro.py", line 234, in upload_download
  File "C:\Program Files (x86)\Odoo 9.0-20160830\server.\openerp\api.py", line 248, in wrapper
  File "C:\Program Files (x86)\Odoo 9.0-20160830\server\openerp\addons\base_synchro\wizard\base_synchro.py", line 73, in synchronize
  File "C:\Program Files (x86)\Odoo 9.0-20160830\server\openerp\addons\base_synchro\wizard\base_synchro.py", line 33, in <lambda>
  File "xmlrpclib.pyc", line 1240, in __call__
  File "xmlrpclib.pyc", line 1599, in __request
  File "xmlrpclib.pyc", line 1280, in request
  File "xmlrpclib.pyc", line 1313, in single_request
  File "xmlrpclib.pyc", line 1490, in parse_response
  File "xmlrpclib.pyc", line 799, in close
Fault: <Fault operator does not exist: integer = boolean
LINE 1: ...T password, password_crypt FROM res_users WHERE id=false AND...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
: 'Traceback (most recent call last):\n  File "C:\\Program Files (x86)\\Odoo 9.0-20160830\\server\\.\\openerp\\service\\wsgi_server.py", line 56, in xmlrpc_return\n  File "C:\\Program Files (x86)\\Odoo 9.0-20160830\\server\\.\\openerp\\http.py", line 115, in dispatch_rpc\n  File "C:\\Program Files (x86)\\Odoo 9.0-20160830\\server\\.\\openerp\\service\\model.py", line 34, in dispatch\n  File "C:\\Program Files (x86)\\Odoo 9.0-20160830\\server\\.\\openerp\\service\\security.py", line 13, in check\n  File "C:\\Program Files (x86)\\Odoo 9.0-20160830\\server\\openerp\\addons\\base\\res\\res_users.py", line 508, in check\n  File "C:\\Program Files (x86)\\Odoo 9.0-20160830\\server\\.\\openerp\\api.py", line 250, in wrapper\n  File "C:\\Program Files (x86)\\Odoo 9.0-20160830\\server\\openerp\\addons\\auth_crypt\\auth_crypt.py", line 51, in check_credentials\n  File "C:\\Program Files (x86)\\Odoo 9.0-20160830\\server\\.\\openerp\\sql_db.py", line 141, in wrapper\n  File "C:\\Program Files (x86)\\Odoo 9.0-20160830\\server\\.\\openerp\\sql_db.py", line 220, in execute\nProgrammingError: operator does not exist: integer = boolean\nLINE 1: ...T password, password_crypt FROM res_users WHERE id=false AND...\n                                                             ^\nHINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.\n\n'>

**Comment by JayVora-SerpentCS** [comment]
We didnt face here, would you please retry with latest code? It seems a prob with data.

**Comment by Lazza** [comment]
I am encountering the same problem on Odoo 8.0 self-hosted. I've downloaded the plug-in straight from the 8.0 branch here on GitHub and the problem persists:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 544, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 581, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 317, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 314, in checked_call
    return self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 810, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 410, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 399, in old_api
    result = method(recs, *args, **kwargs)
  File "/var/lib/odoo/.local/share/Odoo/addons/8.0/base_synchro/wizard/base_synchro.py", line 299, in upload_download_multi_thread
    threaded_synchronization = threading.Thread(target=self.upload_download())
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/var/lib/odoo/.local/share/Odoo/addons/8.0/base_synchro/wizard/base_synchro.py", line 261, in upload_download
    self.synchronize(server, obj_rec)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/var/lib/odoo/.local/share/Odoo/addons/8.0/base_synchro/wizard/base_synchro.py", line 94, in synchronize
    module_id  = module.search(self._cr, self.user_id.id, [("name","ilike","base_synchro"), ('state','=','installed')])
  File "/var/lib/odoo/.local/share/Odoo/addons/8.0/base_synchro/wizard/base_synchro.py", line 49, in <lambda>
    return lambda cr, uid, *args, **kwargs: self.rpc.execute(self.server.server_db, self.uid, self.server.password, self.ressource, name, *args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1316, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1493, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 800, in close
    raise Fault(**self._stack[0])
Fault: <Fault operator does not exist: integer = boolean
LINE 1: ...T password, password_crypt FROM res_users WHERE id=false AND...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
: 'Traceback (most recent call last):\n  File "/usr/lib/python2.7/dist-packages/openerp/service/wsgi_server.py", line 75, in xmlrpc_return\n    result = openerp.http.dispatch_rpc(service, method, params)\n  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 115, in dispatch_rpc\n    result = dispatch(method, params)\n  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 34, in dispatch\n    security.check(db,uid,passwd)\n  File "/usr/lib/python2.7/dist-packages/openerp/service/security.py", line 36, in check\n    return res_users.check(db, uid, passwd)\n  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/res/res_users.py", line 519, in check\n    self.check_credentials(cr, uid, passwd)\n  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 268, in wrapper\n    return old_api(self, *args, **kwargs)\n  File "/usr/lib/python2.7/dist-packages/openerp/addons/auth_crypt/auth_crypt.py", line 51, in check_credentials\n    cr.execute(\'SELECT password, password_crypt FROM res_users WHERE id=%s AND active\', (uid,))\n  File "/usr/lib/python2.7/dist-packages/openerp/sql_db.py", line 158, in wrapper\n    return f(self, *args, **kwargs)\n  File "/usr/lib/python2.7/dist-packages/openerp/sql_db.py", line 234, in execute\n    res = self._obj.execute(query, params)\nProgrammingError: operator does not exist: integer = boolean\nLINE 1: ...T password, password_crypt FROM res_users WHERE id=false AND...\n                                                             ^\nHINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.\n\n'>
```

You cannot have `FROM res_users WHERE id=false`. How can we solve this issue?

Thanks.

**Comment by JayVora-SerpentCS** [comment]
Interesting, I will get it checked with v8. Thanks.

**Comment by Chandresh-SerpentCS** [comment]
Hello @Lazza,
Can you please share your wizard screen with the values which you enters in that with us?
Hint :- (Synchronization -> Synchronization objects)

Thank You.

**Comment by Lazza** [comment]
Thanks, I will try next time I'm at my client's office.

**Comment by ibrahimtoma** [comment]
Hello @JayVora-SerpentCS  ... I Faced the same problem in Odoo9 ... like @Lazza  in V8 ... i searched for solution but don`t reach to any solution... i see merge pull request  #103 from chandresh ...
can i test his solution in Odoo9 !!! If No.
Can U help Me ?
i can send the files what u want.

**Comment by JayVora-SerpentCS** [comment]
@ibrahimtoma Salam. Check with v9, it should work. Meanwhile, do email us for any professional support : contact@serpentcs.com
