### ISSUE TITLE
[9.0] web_one2many_kanban  Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by abdallamhafeez** [JayVora-SerpentCS/SerpentCS_Contributions-v8#63]
This error appear when make group by

http://localhost:9999/web/static/src/js/framework/data.js:157
Traceback:
TypeError: Cannot read property 'split' of undefined
    at http://localhost:9999/web/static/src/js/framework/data.js:157:25
    at Function._.map._.collect (http://localhost:9999/web/static/lib/underscore/underscore.js:164:24)
    at Class.group_by (http://localhost:9999/web/static/src/js/framework/data.js:156:28)
    at Class.load_groups (http://localhost:9999/web_one2many_kanban/static/src/js/web_one2many_kanban.js:209:14)
    at Class.do_search (http://localhost:9999/web_kanban/static/src/js/kanban_view.js:131:41)
    at Object.<anonymous> (http://localhost:9999/web/static/src/js/view_manager.js:439:31)
    at fire (http://localhost:9999/web/static/lib/jquery/jquery.js:3119:58)
    at Object.fireWith [as resolveWith](http://localhost:9999/web/static/lib/jquery/jquery.js:3231:49)
    at Object.deferred.(anonymous function) [as resolve](http://localhost:9999/web/static/lib/jquery/jquery.js:3321:62)
    at http://localhost:9999/web/static/src/js/framework/pyeval.js:1002:11

**Comment by sudhir-serpentcs** [comment]
Hello @abdallamohamed1992 thanks for your comment.
We have fixed the stated issue. Please pull the latest code for the module.
