### ISSUE TITLE
[16.0] Error installing sale_report_hide_price module

### ISSUE THREAD

**Issue by pleirb** [JayVora-SerpentCS/SerpentCS_Contributions-v8#654]
I don't know if anyone had this problem or if it just happens in my odoo due to a different configuration than what odoo brings with a new database. I leave the error here to see if someone can guide me.

```
Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1632, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo/custom/src/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1659, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1863, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/opt/odoo/auto/addons/website/models/ir_http.py", line 237, in _dispatch
    response = super()._dispatch(endpoint)
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 716, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo/auto/addons/web/controllers/dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/auto/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 468, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-77>", line 2, in button_immediate_install
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_module.py", line 475, in button_immediate_install
    return self._button_immediate_function(self.env.registry[self._name].button_install)
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_module.py", line 599, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "<decorator-gen-16>", line 2, in new
  File "/opt/odoo/custom/src/odoo/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/modules/registry.py", line 90, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 488, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 372, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 231, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 71, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/opt/odoo/custom/src/odoo/odoo/tools/convert.py", line 763, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/opt/odoo/custom/src/odoo/odoo/tools/convert.py", line 829, in convert_xml_import
    obj.parse(doc.getroot())
  File "/opt/odoo/custom/src/odoo/odoo/tools/convert.py", line 749, in parse
    self._tag_root(de)
  File "/opt/odoo/custom/src/odoo/odoo/tools/convert.py", line 709, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
odoo.tools.convert.ParseError: while parsing None:4
Ocurrió un error al validar la vista:

El elemento '<td t-if="display_discount" groups="product.group_discount_per_so_line">' no puede ser localizado en la vista padre

View error context:
{'file': '/opt/odoo/auto/addons/sale_report_hide_price/views/report_saleorder.xml',
 'line': 4,
 'name': 'report_sale_document_inherits',
 'view': ir.ui.view(6167,),
 'view.model': False,
 'view.parent': ir.ui.view(497,),
 'xmlid': 'report_sale_document_inherits'}
```

**Comment by Trivedi-Vacha-SerpentCS** [comment]
Hello @pleirb 
Do you have any other custom module installed in your DB? Make sure "display_discount" section should not removed by any other custom app.
What is the different configuration you had in your odoo?

**Comment by pleirb** [comment]
> Hello @pleirb Do you have any other custom module installed in your DB? Make sure "display_discount" section should not removed by any other custom app. What is the different configuration you had in your odoo?

Thanks for responding, yes, I'm still trying to solve the problem. I have checked 2 OCA modules that could be making this change but I proceeded to uninstall and purge and I am still getting the error installing the module. Does it have to do with using Odoo community?

**Comment by Trivedi-Vacha-SerpentCS** [comment]
@pleirb can you check with odoo16 Community version without any custom modules?
If it works, then we need to trace with your custom modules.
