### ISSUE TITLE
Error when try to install project_team:10 module in odoo:10.

### ISSUE THREAD

**Issue by Timothyyy** [JayVora-SerpentCS/SerpentCS_Contributions-v8#72]
When try to install project_team:10 in odoo:10, appears traceback, listed below.
Tested with project_team:9 and odoo:9 - all is fine.

`Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 866, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 854, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/module/module.py", line 410, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/module/module.py", line 484, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/registry.py", line 78, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 337, in load_modules
    loaded_modules, update_module)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 235, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 177, in load_module_graph
    env['ir.ui.view']._validate_module_views(module_name)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 1180, in _validate_module_views
    self.raise_view_error("Can't validate view:\n%s" % (e.message or repr(e)), vid)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 454, in raise_view_error
    raise ValueError(message)
ValueError: Can't validate view:
Field `code` does not exist

Error context:
View `crm.team.form`
[view_id: 448, xml_id: project_team.project_team_form_view, model: crm.team, parent_id: n/a]

Error context:
View `crm.team.form`
[view_id: 448, xml_id: project_team.project_team_form_view, model: crm.team, parent_id: n/a]`

**Comment by JayVora-SerpentCS** [comment]
We have yet to migrate it, but we will do in next week.
Thanks.
