### ISSUE TITLE
short dump when installing in version 10

### ISSUE THREAD

**Issue by ccandito** [JayVora-SerpentCS/SerpentCS_Contributions-v8#89]
Please find below the error log.
regards
claudio candito

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 882, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 870, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/module/module.py", line 410, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/module/module.py", line 484, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/registry.py", line 78, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 339, in load_modules
    loaded_modules, update_module)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 848, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 918, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 799, in parse
    self.parse(rec, mode)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 802, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 710, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_model.py", line 1196, in _update
    record = record.create(values)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 360, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3829, in create
    self._fields[key].determine_inverse(record)
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 999, in determine_inverse
    getattr(records, self.inverse)()
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 220, in _inverse_arch
    view.write(data)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 378, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3555, in write
    self._write(old_vals)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3706, in _write
    self._validate_fields(vals)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 1074, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
ParseError: "Error while validating constraint

Element '<field name="task_ids">' cannot be located in parent view

Error context:
View `project.kanban.view.kanban`
[view_id: 1437, xml_id: n/a, model: project.project, parent_id: 1127]
None" while parsing /usr/lib/python2.7/dist-packages/odoo/addons/project_kanban/views/project_kanban_view.xml:18, near
<record id="project_kanaban_view_kanban" model="ir.ui.view">
            <field name="name">project.kanban.view.kanban</field>
            <field name="model">project.project</field>
            <field name="inherit_id" ref="project.view_project_kanban"/>
            <field name="arch" type="xml">
               <data><field name="task_ids" position="after">
                    <field name="write_date" readonly="1"/>
                    <field name="recent_date"/>
                </field>
                <xpath expr="//div[contains(@class, 'o_kanban_primary_left')]" position="after">
                    <a style="font-size: 10px;">Last updated on:
                        <field name="write_date"/>
                    </a>
                </xpath> 
                <xpath expr="//div[contains(@class, 'o_kanban_primary_left')]" position="after">
                    <div style="font-size: 10px;">
                        <a>Recent Log Date:
                            <field name="recent_date" string="Recent Date"/>
                        </a>
                    </div>
                </xpath>
            </data></field>
        </record>

**Comment by JayVora-SerpentCS** [comment]
@ccandito strange, we did not face! Please tell what modules of project you are using?

**Comment by ccandito** [comment]
I've installed the project module and
Project Team v10	Serpent Consulting Services Pvt. Ltd.	10.0.1.0.0	Installed
Project	Odoo S.A.	10.0.1.1	Installed
Project Category	ADHOC SA,Stella Fredö in Sweden upgraded it V10	10.0.1.0.0	Installed
Project Description	Antiun Ingeniería S.L., Tecnativa, Odoo Community Association (OCA)	10.0.1.0.0	Installed
Add State field to Project Stages	Daniel Reis,Odoo Community Association (OCA)	10.0.1.0.0	Installed
Project Task Add Very High	Onestein	10.0.1.0.0	Installed
Project Task Default Stage	Tecnativa, Odoo Community Association (OCA)	10.0.1.0.0	Installed
Project Task Dependencies	Onestein,Odoo Community Association (OCA)	10.0.1.0.0	Installed
Task Statusbar	Cybrosys Techno Solutions	10.0.0.3	Installed

Regards
claudio candito

**Comment by JayVora-SerpentCS** [comment]
I doubt this is due to the other OCA modules which make the code incompatbile. Reaosn being, the modules are installed first and hence our module does not find the parent fields we seek for.

**Comment by JayVora-SerpentCS** [comment]
If you are technical, would you please check the inherited views?

**Comment by ccandito** [comment]
unfortunately, I'm not so technical, please detail which steps I should do for providing you all pieces of information you need
Regards
claudio candito

**Comment by JayVora-SerpentCS** [comment]
Actually, the modules you installed are a conflict of interest.
All the modules alter the actual view of project and some might have even removed base view(which is a bad practice), hence we will never end up succeeding here for all cases.
If you are on a production server, we will surely give you a professional support anytime.

**Comment by JayVora-SerpentCS** [comment]
Modules, being from different author is again an issue.

**Comment by JayVora-SerpentCS** [comment]
Closing for now.
